const allResistCards = [
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    '+1 liberation',
    'heal 1',
    'heal 1',
    'heal 1',
    'heal 1',
    'heal 1',
    'heal 1',
    'heal 2',
    'heal 2',
    'heal 2',
    'heal 2',
    '-2 fascists',
    '-2 fascists',
    '-2 fascists',
    '-2 fascists',
    '-2 fascists',
    'teleport',
    'teleport',
    'teleport',
    'ears',
    'paw',
    'tail',
    'whiskers',
    'ears',
    'paw',
    'tail',
    'whiskers',
    'ears',
    'paw',
    'tail',
    'whiskers',
    'ears',
    'paw',
    'tail',
    'whiskers',
    'ears',
    'paw',
    'tail',
    'whiskers',
]

const player = 1;

export {allResistCards, player};